doctrine:
    dbal:
        types:
            uuid_binary_ordered_time: Ramsey\Uuid\Doctrine\UuidBinaryOrderedTimeType
        mapping_types:
            uuid_binary_ordered_time: binary    
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            PlanBEdgeBundle:
                is_bundle: true
                type: xml
                prefix: PlanB\Edge\Domain
                dir: 'Resources/config/mapping/doctrine'
                alias: PlanB\Edge\Domain
