doctrine:
    dbal:
        types:
            date: PlanB\Edge\Infrastructure\Doctrine\DBAL\Type\CarbonDateType
            date_immutable: PlanB\Edge\Infrastructure\Doctrine\DBAL\Type\CarbonDateImmutableType
            datetime: PlanB\Edge\Infrastructure\Doctrine\DBAL\Type\CarbonDateTimeType
            datetime_immutable: PlanB\Edge\Infrastructure\Doctrine\DBAL\Type\CarbonDateTimeImmutableType

            time: PlanB\Edge\Infrastructure\Doctrine\DBAL\Type\CarbonTimeType
            time_immutable: PlanB\Edge\Infrastructure\Doctrine\DBAL\Type\CarbonTimeImmutableType

            uuid_binary_ordered_time: Ramsey\Uuid\Doctrine\UuidBinaryOrderedTimeType


        mapping_types:
            uuid_binary_ordered_time: binary
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            PlanBEdgeBundle:
                is_bundle: true
                type: xml
                prefix: PlanB\Edge\Domain
                dir: 'Resources/config/mapping/doctrine'
                alias: PlanB\Edge\Domain
