RootMutation:
    type: object
    config:
        description: 'root mutation'
        fields:
            create_tag:
                resolve: "@=resolver('create_tag', [args])"
                type: 'Tag'
                args:
                    tag: 'String'
            update_tag:
                resolve: "@=resolver('update_tag', [args])"
                type: 'Tag'
                args:
                    id: 'String!'
                    tag: 'String'                        
            
