RootQuery:
    type: object
    config:
        description: 'root query'
        fields:
            all_tags:
                type: '[Tag]'
                resolve: "@=resolver('all_tags', [args])"

            stats_by_user:
                type: '[Stat]'
                args:
                    userId:
                        type: "String"                
                resolve: "@=resolver('stats_by_user', [args['userId']])"
            
            questions_by_tag:
                type: '[Question]'
                args:
                    userId:
                        type: "String"
                    limit:
                        type: "Int"
                    level:
                        type: "Int"
                    tags:
                        type: '[String]'
                resolve: "@=resolver('questions_by_tag', [args['userId'], args['limit'], args['level'], args['tags']])"

            exam:
                type: '[Question]'
                args:
                    userId:
                        type: "String"
                    type:
                        type: "String"                        
                    limit:
                        type: "Int"
                    tags:
                        type: '[String]'

                resolve: "@=resolver('exam', [args['userId'], args['type'], args['limit'], args['tags']])"
