RootQuery:
    type: object
    config:
        description: 'root query'
        fields:
            all_tags:
                type: '[Tag]'
                resolve: "@=resolver('all_tags', [args])"            
            questions_by_tag:
                type: '[Question]'
                args:
                    tags: 
                        type: '[String]'
                resolve: "@=resolver('questions_by_tag', [args])"

