Tag:
    type: object
    config:
        description: "A tag"
        fields:
            id:
                type: "String"
                description: "The ID of the tag."
            tag:
                type: "String"
                description: "the tag"
                                
