SolveQuestion:
    type: input-object
    config:
        fields:
            user:
                type: "String!"
            question:
                type: "String!"
            response:
                type: "String"                
            dryRun:
                type: "Boolean"                
