formatter.name: pretty
suites:
    PlanB:
        namespace: PlanB
        src_path: "%paths.config%/src"
        spec_path: "%paths.config%"

    LearnWords:
        namespace: LearnWords
        src_path: "%paths.config%/src"
        spec_path: "%paths.config%"

extensions:
    FriendsOfPhpSpec\PhpSpec\CodeCoverage\CodeCoverageExtension:
        output:
            html: build/coverage
            
        whitelist:
            - src
            
        blacklist:
            - src/PlanB/EdgeBundle
            - src/LearnWords/Infrastructure/UI
            - src/LearnWords/Kernel.php
