version: '3.4'
services:
  php:
    #    build:
    #      args:
    #        - WITH_XDEBUG=true
    #
    build:
      context: .
      target: planb_php_dev    
    environment:
      - APP_ENV=dev
      - APP_DEBUG=true
      - PHP_IDE_CONFIG=serverName=symfony-demo
      - XDEBUG_CONFIG=remote_host=192.168.1.128

  db:
    ports:
      - "3306:3306"

  proxy:
    environment:
      CLIENT_MAX_BODY_SIZE: 64M
      DOMAINS: "${DOCKER_PROXY_DOMAINS}"


