<?php

namespace spec\PlanB\Edge\Infrastructure\Sonata\Admin;

use PhpSpec\ObjectBehavior;
use PlanB\Edge\Application\UseCase\DeleteCommand;
use PlanB\Edge\Application\UseCase\SaveCommand;
use PlanB\Edge\Application\UseCase\WriteCommandInterface;
use PlanB\Edge\Domain\Entity\EntityInterface;
use PlanB\Edge\Infrastructure\Sonata\Admin\Admin;
use PlanB\Edge\Infrastructure\Sonata\Configurator\DatagridConfigurator;
use PlanB\Edge\Infrastructure\Sonata\Configurator\DatagridConfiguratorInterface;
use PlanB\Edge\Infrastructure\Sonata\Configurator\FormConfiguratorInterface;
use Prophecy\Argument;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;

class AdminSpec extends ObjectBehavior
{
    public function let()
    {
        $this->beAnInstanceOf(Dummy::class);
        $this->beConstructedWith('admin.code', 'admin.className');

    }

    public function it_is_initializable()
    {
        $this->shouldHaveType(Admin::class);
    }

    public function it_is_able_to_configure_a_form(FormConfiguratorInterface $formConfigurator, FormMapper $formMapper)
    {
        $formConfigurator->handle($formMapper, Argument::any())->shouldBeCalled();

        $this->setFormConfigurator($formConfigurator);
        $this->configureFormFields($formMapper);


    }

    public function it_is_able_to_configure_a_datagrid(DatagridConfiguratorInterface $datagridConfigurator, ListMapper $listMapper)
    {
        $datagridConfigurator->handle($listMapper)->shouldBeCalled();

        $this->setDatagridConfigurator($datagridConfigurator);
        $this->configureListFields($listMapper);
    }

    public function it_returns_a_correct_base_route_name(){
        $this->getBaseRouteName()->shouldReturn('admin_admin.classname');
    }

    public function it_returns_a_correct_base_route_pattern(){
        $this->getBaseRoutePattern()->shouldReturn('admin.classname');
    }

}

class Dummy extends Admin
{
    public function configureFormFields(FormMapper $formMapper): void
    {
        parent::configureFormFields($formMapper);
    }

    public function configureListFields(ListMapper $listMapper): void
    {
        parent::configureListFields($listMapper); // TODO: Change the autogenerated stub
    }

    public function deleteCommand(EntityInterface $entity): DeleteCommand
    {
    }

    public function saveCommand(array $input, ?EntityInterface $entity): SaveCommand
    {
    }
}
