doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)        
        #server_version: '5.8'

        types:
            Lang: LearnWords\Infrastructure\Domain\Dictionary\DBAL\LangType
            Relevance: LearnWords\Infrastructure\Domain\Dictionary\DBAL\RelevanceType
            Mp3Url: LearnWords\Infrastructure\Domain\Dictionary\DBAL\Mp3UrlType
            EntryId: LearnWords\Infrastructure\Domain\Dictionary\DBAL\EntryIdType
            TagId: LearnWords\Infrastructure\Domain\Dictionary\DBAL\TagIdType
            QuestionId: LearnWords\Infrastructure\Domain\Dictionary\DBAL\QuestionIdType

        mapping_types:
            Relevance: integer
            Mp3Url: string
            EntryId: string
            TagId: string
            QuestionId: string
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Word:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/LearnWords/Infrastructure/Domain/Dictionary/Mapping/ORM'
                prefix: 'LearnWords\Domain\Dictionary'
