doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)        
        #server_version: '5.8'

        types:
            lang: LearnWords\Infrastructure\Domain\Term\DBAL\LangType
            TermId: LearnWords\Infrastructure\Domain\Term\DBAL\TermIdType
            
            TagId: LearnWords\Infrastructure\Domain\Tag\DBAL\TagIdType

        mapping_types:
            lang: string
            TermId: string
            TagId: string
            
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Term:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/LearnWords/Infrastructure/Domain/Term/Mapping/ORM'
                prefix: 'LearnWords\Domain\Term'
            Tag:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/LearnWords/Infrastructure/Domain/Tag/Mapping/ORM'
                prefix: 'LearnWords\Domain\Tag'

