overblog_graphql:
    definitions:
        schema:
            query: RootQuery
            mutation: RootMutation
        mappings:
            auto_discover: false
            types:
                -   type: yaml
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: ~
