framework:
    serializer:
        enabled: true
        mapping:
            paths:
                - '%kernel.project_dir%/src/LearnWords/Infrastructure/Domain/Term/Mapping/Serializer'
                - '%kernel.project_dir%/src/LearnWords/Infrastructure/Domain/Tag/Mapping/Serializer'
