sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    options:
        legacy_twig_text_extension: false

#    admin_services:
#        admin.dummy:
#            form_contractor:  sonata.admin.builder.doctrine_orm
sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
