query($userId: String!, $type:String!, $limit:Int, $tags:[String]){
  exam(userId: $userId, type: $type, limit: $limit, tags:$tags){
    id
    word
    wording
    description
    sample
    translation
    sound
  }
}
