query($userId: String, $limit: Int, $level: Int, $tags: [String]){
  questions_by_tag (userId:$userId, limit:$limit, level:$level, tags:$tags){
    id
    word
    wording
    description
    sample
    translation
    sound
  }
}
